## Ders Plani
1. groupby kullanimi
2. agg kullanimi
3. merge kullanimi
4. transform kullanimi
5. concat kullanimi
6. pivot tablosu kullanimi
7. tablonun csv olarak kaydedilmesi

---

# Pandas ile Veri Manipülasyonu ve Analizi

Pandas, Python'da veri analizi ve manipülasyonu için vazgeçilmez bir kütüphanedir. Özellikle tablo biçimindeki verilerle (DataFrame'ler) çalışmak için tasarlanmıştır. Bu dokümanda, Pandas'ın en sık kullanılan ve güçlü özelliklerinden bazılarını detaylıca inceleyeceğiz.

---

## 1. `groupby()` Kullanımı

**`groupby()`** fonksiyonu, veri çerçevesini (DataFrame) belirli kriterlere göre **gruplara ayırmak** ve ardından her grup üzerinde bağımsız olarak işlemler yapmak için kullanılır. SQL'deki `GROUP BY` ifadesine benzer bir işlevi vardır.

**İşleyiş:**

1.  **Bölme (Splitting):** DataFrame, bir veya daha fazla sütunun benzersiz değerlerine göre parçalara (gruplara) ayrılır.
2.  **Uygulama (Applying):** Her bir bağımsız grup üzerinde bir fonksiyon (toplama, ortalama alma, sayma vb.) uygulanır.
3.  **Birleştirme (Combining):** Her grup için uygulanan fonksiyonun sonuçları tek bir sonuç veri yapısında birleştirilir.

**Örnek:**

```python
import pandas as pd
import numpy as np

data = {'Bölge': ['Kuzey', 'Güney', 'Kuzey', 'Doğu', 'Güney', 'Batı', 'Doğu', 'Kuzey'],
        'Ürün': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B'],
        'Satış': [100, 150, 120, 80, 200, 110, 90, 130],
        'Maliyet': [50, 70, 60, 40, 90, 55, 45, 65]}
df = pd.DataFrame(data)

print("Orjinal DataFrame:")
print(df)
print("\n" + "="*50 + "\n")

# Tek bir sütuna göre gruplama ve toplam satışları bulma
toplam_satis_bolgeye_gore = df.groupby('Bölge')['Satış'].sum()
print("Bölgelere göre toplam satışlar:\n", toplam_satis_bolgeye_gore)
print("\n" + "="*50 + "\n")

# Birden fazla sütuna göre gruplama ve ortalama satışları bulma
ortalama_satis_bolge_urun_gore = df.groupby(['Bölge', 'Ürün'])['Satış'].mean()
print("Bölge ve Ürüne göre ortalama satışlar:\n", ortalama_satis_bolge_urun_gore)
print("\n" + "="*50 + "\n")
```

---

## 2. `agg()` Kullanımı

**`agg()`** (aggregate) fonksiyonu, DataFrame'inizdeki bir veya daha fazla sütun üzerinde **birden çok farklı toplama işlemi** yapmanızı sağlar. Genellikle `groupby()` ile birlikte kullanılarak gruplanmış veriler üzerinde özet istatistikler oluşturmak için tercih edilir.

**Kullanım Çeşitleri:**

* **Tek sütun, birden fazla işlem:** Bir sütun üzerinde aynı anda ortalama, standart sapma gibi birden fazla istatistik hesaplama.
* **Farklı sütunlarda farklı işlemler:** Her sütuna özel toplama fonksiyonları atama.
* **`groupby()` ile:** Gruplanmış veriler için çok yönlü özetler oluşturma.

**Örnek:**

```python
# 'Bölge'ye göre gruplayıp 'Satış' ve 'Maliyet' için farklı istatistikler alma
grup_istatistikleri = df.groupby('Bölge').agg(
    toplam_satis=('Satış', 'sum'),           # Satışların toplamı
    ortalama_maliyet=('Maliyet', 'mean'),   # Maliyetlerin ortalaması
    satis_sayisi=('Satış', 'count'),         # Satışların adedi
    en_yuksek_satis=('Satış', 'max')         # En yüksek satış
)

print("Bölgelere göre çeşitli istatistikler (agg kullanımı):\n", grup_istatistikleri)
print("\n" + "="*50 + "\n")

# Tek sütun üzerinde birden fazla işlem (groupby olmadan)
deger_istatistikleri = df['Satış'].agg(['sum', 'mean', 'std'])
print("Satış sütunu için toplam, ortalama ve standart sapma:\n", deger_istatistikleri)
print("\n" + "="*50 + "\n")
```

---

## 3. `merge()` Kullanımı

**`merge()`** fonksiyonu, SQL'deki `JOIN` işlemlerine benzer şekilde, **iki DataFrame'i bir veya daha fazla ortak sütuna (anahtar) göre birleştirmek** için kullanılır. Farklı birleştirme türlerini (inner, outer, left, right) destekler.

**Temel Parametreler:**

* **`right`:** Birleştirilecek ikinci DataFrame.
* **`how`:** Birleştirme türü (`'inner'`, `'outer'`, `'left'`, `'right'`). Varsayılan `'inner'`.
* **`on`:** Birleştirme için kullanılacak sütun veya sütunların adı (eğer her iki DataFrame'de de aynı isimdeyse).
* **`left_on` / `right_on`:** Eğer birleştirme sütunları farklı isimdeyse, sol ve sağ DataFrame'deki sütun adları.

**Örnek:**

```python
# İkinci bir DataFrame oluşturalım
urun_bilgileri = pd.DataFrame({
    'Ürün': ['A', 'B', 'C', 'D'],
    'Kategori': ['Elektronik', 'Giyim', 'Gıda', 'Elektronik'],
    'Fiyat': [1000, 200, 50, 500]
})

print("Ürün Bilgileri DataFrame:")
print(urun_bilgileri)
print("\n" + "="*50 + "\n")

# 'df' ile 'urun_bilgileri' DataFrame'lerini 'Ürün' sütununa göre birleştirme (inner join)
birlesik_df = pd.merge(df, urun_bilgileri, on='Ürün', how='inner')
print("df ve urun_bilgileri DataFrame'lerinin 'Ürün'e göre birleşimi (inner):\n", birlesik_df)
print("\n" + "="*50 + "\n")

# Sol birleştirme (left join) - df'deki tüm kayıtlar ve eşleşen ürün bilgileri
sol_birlesim = pd.merge(df, urun_bilgileri, on='Ürün', how='left')
print("df ve urun_bilgileri DataFrame'lerinin 'Ürün'e göre sol birleşimi:\n", sol_birlesim)
print("\n" + "="*50 + "\n")
```

---

## 4. `transform()` Kullanımı

**`transform()`** fonksiyonu, `groupby()` ile birlikte kullanıldığında çok faydalıdır. Bir gruba ait değerler üzerinde bir hesaplama yapar ve bu **sonucu orijinal DataFrame'in boyutuyla aynı olacak şekilde geri döndürür**. Bu, gruplama sonrası sonuçları orijinal DataFrame'e yeni sütunlar olarak eklemek için idealdir.

**`agg()` ile Farkı:**

* `agg()`: Her grup için **tek bir özet değer** döndürür, bu da orijinal DataFrame'den daha küçük bir çıktıya neden olur.
* `transform()`: Her grubun hesaplanmış değerini **orijinal DataFrame'in her bir satırına karşılık gelecek şekilde** döndürür, böylece orijinal DataFrame ile aynı boyutta bir Series veya DataFrame elde edilir.

**Örnek:**

```python
# Her bölgedeki satışların ortalamasını hesapla ve orijinal DataFrame'e ekle
df['Bölge_Ort_Satış'] = df.groupby('Bölge')['Satış'].transform('mean')

print("Bölgelere göre ortalama satışlar, transform ile orijinal DataFrame'e eklendi:\n", df)
print("\n" + "="*50 + "\n")

# Her bölgedeki satışların toplamını hesapla ve orijinal DataFrame'e ekle
df['Bölge_Toplam_Satış'] = df.groupby('Bölge')['Satış'].transform('sum')

print("Bölgelere göre toplam satışlar, transform ile orijinal DataFrame'e eklendi:\n", df)
print("\n" + "="*50 + "\n")
```

---

## 5. `concat()` Kullanımı

**`concat()`** fonksiyonu, Pandas nesnelerini (Series veya DataFrame'ler) **dikey veya yatay olarak birleştirmek** için kullanılır. `merge()`'den farklı olarak, `concat()` anahtar sütunlara ihtiyaç duymaz; daha çok yığınlama veya yan yana birleştirme işlemi yapar.

**Temel Parametreler:**

* **`objs`:** Birleştirilecek Pandas nesnelerinin listesi.
* **`axis`:** Birleştirme ekseni. `0` (varsayılan) dikey birleştirme (satır ekleme), `1` ise yatay birleştirme (sütun ekleme).
* **`join`:** Birleştirme türü (`'outer'` varsayılan, `'inner'`).
* **`ignore_index`:** `True` ise, sonuç DataFrame'in indeksini sıfırlar.

**Örnek:**

```python
# İki yeni DataFrame oluşturalım
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df3 = pd.DataFrame({'C': [9, 10], 'D': [11, 12]})

print("df1:\n", df1)
print("\ndf2:\n", df2)
print("\ndf3:\n", df3)
print("\n" + "="*50 + "\n")

# Dikey birleştirme (satır ekleme)
dikey_birlesim = pd.concat([df1, df2])
print("df1 ve df2'nin dikey birleşimi:\n", dikey_birlesim)
print("\n" + "="*50 + "\n")

# Dikey birleştirme ve indeksi sıfırlama
dikey_birlesim_sifirlanmis_index = pd.concat([df1, df2], ignore_index=True)
print("df1 ve df2'nin dikey birleşimi (indeks sıfırlanmış):\n", dikey_birlesim_sifirlanmis_index)
print("\n" + "="*50 + "\n")

# Yatay birleştirme (sütun ekleme)
yatay_birlesim = pd.concat([df1, df3], axis=1)
print("df1 ve df3'ün yatay birleşimi:\n", yatay_birlesim)
print("\n" + "="*50 + "\n")
```

---

## 6. Pivot Tablosu Kullanımı (`pivot_table()`)

Pandas'taki **`pivot_table()`** fonksiyonu, Excel'deki pivot tablolarına benzer şekilde çalışır. Verileri özetlemek, yeniden şekillendirmek ve farklı perspektiflerden analiz etmek için kullanılır. Genellikle büyük ve karmaşık veri setlerinden özetlenmiş, okunabilir tablolar oluşturmak için idealdir.

**Temel Parametreler:**

* **`values`:** Pivot tablosunda gösterilecek değerleri içeren sütun(lar).
* **`index`:** Yeni tablonun satır indeksini oluşturacak sütun(lar).
* **`columns`:** Yeni tablonun sütun başlıklarını oluşturacak sütun(lar).
* **`aggfunc`:** Uygulanacak toplama fonksiyonu (örneğin, `'mean'`, `'sum'`, `np.sum`, `len`). Varsayılan `'mean'`.
* **`fill_value`:** Eksik değerleri (NaN) doldurmak için kullanılacak değer.

**Örnek:**

```python
print("Orjinal DataFrame (tekrar gösterim):\n", df)
print("\n" + "="*50 + "\n")

# Bölgelere göre ürünlerin ortalama satışlarını gösteren bir pivot tablosu
pivot_satis_ortalama = pd.pivot_table(df, values='Satış', index='Bölge', columns='Ürün', aggfunc='mean')
print("Bölgelere göre ürünlerin ortalama satışları (Pivot Tablo):\n", pivot_satis_ortalama)
print("\n" + "="*50 + "\n")

# Bölgelere göre ürünlerin toplam satışlarını gösteren ve NaN değerleri 0 ile dolduran pivot tablosu
pivot_satis_toplam = pd.pivot_table(df, values='Satış', index='Bölge', columns='Ürün', aggfunc='sum', fill_value=0)
print("Bölgelere göre ürünlerin toplam satışları (Pivot Tablo, NaN=0):\n", pivot_satis_toplam)
print("\n" + "="*50 + "\n")
```

---

## 7. Tablonun CSV Olarak Kaydedilmesi (`to_csv()`)

Veri analizi sonuçlarınızı veya manipüle ettiğiniz DataFrame'i daha sonra kullanmak veya başkalarıyla paylaşmak için bir CSV (Comma Separated Values) dosyasına kaydetmek yaygın bir işlemdir. Pandas'taki **`to_csv()`** fonksiyonu bu görevi kolayca yerine getirir.

**Temel Parametreler:**

* **`path_or_buf`:** Dosyanın kaydedileceği yol ve adı (örn: `'analiz_sonuclari.csv'`).
* **`sep`:** Ayırıcı karakter (varsayılan virgül `,`).
* **`index`:** `True` ise DataFrame indeksi de dosyaya kaydedilir. `False` ise kaydedilmez.
* **`header`:** `True` ise sütun başlıkları kaydedilir.
* **`encoding`:** Dosya kodlaması (örn: `'utf-8'`).

**Örnek:**

```python
# Önceki pivot tablo sonucunu bir CSV dosyasına kaydedelim
output_filename = 'bolge_urun_satis_ozeti.csv'
pivot_satis_toplam.to_csv(output_filename, index=True, encoding='utf-8')

print(f"'{output_filename}' dosyası başarıyla kaydedildi.")

# Kaydedilen dosyayı okuyarak kontrol edelim (isteğe bağlı)
# loaded_df = pd.read_csv(output_filename, index_col=0) # İlk sütunu indeks olarak oku
# print("\nKaydedilen ve tekrar okunan DataFrame:")
# print(loaded_df)
```

Bu doküman, Pandas'ın en temel ve yaygın kullanılan fonksiyonlarını kapsıyor. Bu araçlar, veri temizleme, düzenleme, özetleme ve analiz etme süreçlerinizde size büyük kolaylık sağlayacaktır.

In [ ]:
import pandas as pd
import numpy as np

data = {'Bölge': ['Kuzey', 'Güney', 'Kuzey', 'Doğu', 'Güney', 'Batı', 'Doğu', 'Kuzey'],
        'Ürün': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B'],
        'Satış': [100, 150, 120, 80, 200, 110, 90, 130],
        'Maliyet': [50, 70, 60, 40, 90, 55, 45, 65]}
df = pd.DataFrame(data)

print("Orjinal DataFrame:")
df

Orjinal DataFrame:

   Bölge Ürün  Satış  Maliyet
0  Kuzey    A    100       50
1  Güney    B    150       70
2  Kuzey    A    120       60
3   Doğu    C     80       40
4  Güney    B    200       90
5   Batı    A    110       55
6   Doğu    C     90       45
7  Kuzey    B    130       65

In [ ]:
# Tek bir sütuna göre gruplama ve toplam satışları bulma
toplam_satis_bolgeye_gore = df.groupby('Bölge')['Satış'].sum()
print("Bölgelere göre toplam satışlar:\n")
toplam_satis_bolgeye_gore

Bölgelere göre toplam satışlar:

Bölge
Batı     110
Doğu     170
Güney    350
Kuzey    350
Name: Satış, dtype: int64

In [ ]:
# Birden fazla sütuna göre gruplama ve ortalama satışları bulma
ortalama_satis_bolge_urun_gore = df.groupby(['Bölge', 'Ürün'])['Satış'].mean()
print("Bölge ve Ürüne göre ortalama satışlar:\n")
ortalama_satis_bolge_urun_gore

Bölge ve Ürüne göre ortalama satışlar:

Bölge  Ürün
Batı   A       110.0
Doğu   C        85.0
Güney  B       175.0
Kuzey  A       110.0
       B       130.0
Name: Satış, dtype: float64

In [ ]:
# 'Bölge'ye göre gruplayıp 'Satış' ve 'Maliyet' için farklı istatistikler alma
grup_istatistikleri = df.groupby('Bölge').agg(
    toplam_satis=('Satış', 'sum'),           # Satışların toplamı
    ortalama_maliyet=('Maliyet', 'mean'),   # Maliyetlerin ortalaması
    satis_sayisi=('Satış', 'count'),         # Satışların adedi
    en_yuksek_satis=('Satış', 'max')         # En yüksek satış
)

print("Bölgelere göre çeşitli istatistikler (agg kullanımı):\n")
grup_istatistikleri

Bölgelere göre çeşitli istatistikler (agg kullanımı):

       toplam_satis  ortalama_maliyet  satis_sayisi  en_yuksek_satis
Bölge
Batı            110         55.000000             1              110
Doğu            170         42.500000             2               90
Güney           350         80.000000             2              200
Kuzey           350         58.333333             3              130

In [ ]:
# Tek sütun üzerinde birden fazla işlem (groupby olmadan)
deger_istatistikleri = df['Satış'].agg(['sum', 'mean', 'std'])
print("Satış sütunu için toplam, ortalama ve standart sapma:\n")
deger_istatistikleri

Satış sütunu için toplam, ortalama ve standart sapma:

sum     980.000000
mean    122.500000
std      38.452197
Name: Satış, dtype: float64

In [ ]:
# İkinci bir DataFrame oluşturalım
urun_bilgileri = pd.DataFrame({
    'Ürün': ['A', 'B', 'C', 'D'],
    'Kategori': ['Elektronik', 'Giyim', 'Gıda', 'Elektronik'],
    'Fiyat': [1000, 200, 50, 500]
})

print("Ürün Bilgileri DataFrame:")
urun_bilgileri

Ürün Bilgileri DataFrame:

  Ürün    Kategori  Fiyat
0    A  Elektronik   1000
1    B       Giyim    200
2    C        Gıda     50
3    D  Elektronik    500

In [ ]:


# 'df' ile 'urun_bilgileri' DataFrame'lerini 'Ürün' sütununa göre birleştirme (inner join)
birlesik_df = pd.merge(df, urun_bilgileri, on='Ürün', how='inner')
print("df ve urun_bilgileri DataFrame'lerinin 'Ürün'e göre birleşimi (inner):\n")
birlesik_df

df ve urun_bilgileri DataFrame'lerinin 'Ürün'e göre birleşimi (inner):

   Bölge Ürün  Satış  Maliyet    Kategori  Fiyat
0  Kuzey    A    100       50  Elektronik   1000
1  Güney    B    150       70       Giyim    200
2  Kuzey    A    120       60  Elektronik   1000
3   Doğu    C     80       40        Gıda     50
4  Güney    B    200       90       Giyim    200
5   Batı    A    110       55  Elektronik   1000
6   Doğu    C     90       45        Gıda     50
7  Kuzey    B    130       65       Giyim    200

In [ ]:
# Sol birleştirme (left join) - df'deki tüm kayıtlar ve eşleşen ürün bilgileri
sol_birlesim = pd.merge(df, urun_bilgileri, on='Ürün', how='left')
print("df ve urun_bilgileri DataFrame'lerinin 'Ürün'e göre sol birleşimi:\n")
sol_birlesim

df ve urun_bilgileri DataFrame'lerinin 'Ürün'e göre sol birleşimi:

   Bölge Ürün  Satış  Maliyet    Kategori  Fiyat
0  Kuzey    A    100       50  Elektronik   1000
1  Güney    B    150       70       Giyim    200
2  Kuzey    A    120       60  Elektronik   1000
3   Doğu    C     80       40        Gıda     50
4  Güney    B    200       90       Giyim    200
5   Batı    A    110       55  Elektronik   1000
6   Doğu    C     90       45        Gıda     50
7  Kuzey    B    130       65       Giyim    200

In [ ]:
# Her bölgedeki satışların ortalamasını hesapla ve orijinal DataFrame'e ekle
df['Bölge_Ort_Satış'] = df.groupby('Bölge')['Satış'].transform('mean')

print("Bölgelere göre ortalama satışlar, transform ile orijinal DataFrame'e eklendi:\n")
df

Bölgelere göre ortalama satışlar, transform ile orijinal DataFrame'e eklendi:

   Bölge Ürün  Satış  Maliyet  Bölge_Ort_Satış
0  Kuzey    A    100       50       116.666667
1  Güney    B    150       70       175.000000
2  Kuzey    A    120       60       116.666667
3   Doğu    C     80       40        85.000000
4  Güney    B    200       90       175.000000
5   Batı    A    110       55       110.000000
6   Doğu    C     90       45        85.000000
7  Kuzey    B    130       65       116.666667

In [ ]:
# Her bölgedeki satışların toplamını hesapla ve orijinal DataFrame'e ekle
df['Bölge_Toplam_Satış'] = df.groupby('Bölge')['Satış'].transform('sum')

print("Bölgelere göre toplam satışlar, transform ile orijinal DataFrame'e eklendi:\n")
df

Bölgelere göre toplam satışlar, transform ile orijinal DataFrame'e eklendi:

   Bölge Ürün  Satış  Maliyet  Bölge_Ort_Satış  Bölge_Toplam_Satış
0  Kuzey    A    100       50       116.666667                 350
1  Güney    B    150       70       175.000000                 350
2  Kuzey    A    120       60       116.666667                 350
3   Doğu    C     80       40        85.000000                 170
4  Güney    B    200       90       175.000000                 350
5   Batı    A    110       55       110.000000                 110
6   Doğu    C     90       45        85.000000                 170
7  Kuzey    B    130       65       116.666667                 350

In [ ]:
# İki yeni DataFrame oluşturalım
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df3 = pd.DataFrame({'C': [9, 10], 'D': [11, 12]})


df1

   A  B
0  1  3
1  2  4

In [ ]:
df2

   A  B
0  5  7
1  6  8

In [ ]:
df3

    C   D
0   9  11
1  10  12

In [ ]:

# Dikey birleştirme (satır ekleme)
dikey_birlesim = pd.concat([df1, df2])
print("df1 ve df2'nin dikey birleşimi:\n")
dikey_birlesim

df1 ve df2'nin dikey birleşimi:

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [ ]:

# Dikey birleştirme ve indeksi sıfırlama
dikey_birlesim_sifirlanmis_index = pd.concat([df1, df2], ignore_index=True)
print("df1 ve df2'nin dikey birleşimi (indeks sıfırlanmış):\n")
dikey_birlesim_sifirlanmis_index

df1 ve df2'nin dikey birleşimi (indeks sıfırlanmış):

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [ ]:
# Yatay birleştirme (sütun ekleme)
yatay_birlesim = pd.concat([df1, df3], axis=1)
print("df1 ve df3'ün yatay birleşimi:\n")
yatay_birlesim

df1 ve df3'ün yatay birleşimi:

   A  B   C   D
0  1  3   9  11
1  2  4  10  12

In [ ]:
df

   Bölge Ürün  Satış  Maliyet  Bölge_Ort_Satış  Bölge_Toplam_Satış
0  Kuzey    A    100       50       116.666667                 350
1  Güney    B    150       70       175.000000                 350
2  Kuzey    A    120       60       116.666667                 350
3   Doğu    C     80       40        85.000000                 170
4  Güney    B    200       90       175.000000                 350
5   Batı    A    110       55       110.000000                 110
6   Doğu    C     90       45        85.000000                 170
7  Kuzey    B    130       65       116.666667                 350

In [ ]:
# Bölgelere göre ürünlerin ortalama satışlarını gösteren bir pivot tablosu
pivot_satis_ortalama = pd.pivot_table(df, values='Satış', index='Bölge', columns='Ürün', aggfunc='mean')
print("Bölgelere göre ürünlerin ortalama satışları (Pivot Tablo):\n")
pivot_satis_ortalama

Bölgelere göre ürünlerin ortalama satışları (Pivot Tablo):

Ürün       A      B     C
Bölge
Batı   110.0    NaN   NaN
Doğu     NaN    NaN  85.0
Güney    NaN  175.0   NaN
Kuzey  110.0  130.0   NaN

In [ ]:

# Bölgelere göre ürünlerin toplam satışlarını gösteren ve NaN değerleri 0 ile dolduran pivot tablosu
pivot_satis_toplam = pd.pivot_table(df, values='Satış', index='Bölge', columns='Ürün', aggfunc=['mean'], fill_value=0)
print("Bölgelere göre ürünlerin toplam satışları (Pivot Tablo, NaN=0):\n")
pivot_satis_toplam

Bölgelere göre ürünlerin toplam satışları (Pivot Tablo, NaN=0):

        mean
Ürün       A      B     C
Bölge
Batı   110.0    0.0   0.0
Doğu     0.0    0.0  85.0
Güney    0.0  175.0   0.0
Kuzey  110.0  130.0   0.0

In [ ]:

# Bölgelere göre ürünlerin toplam satışlarını gösteren ve NaN değerleri 0 ile dolduran pivot tablosu
pivot_satis_toplam = pd.pivot_table(df, values=['Satış','Maliyet'], index='Bölge', columns='Ürün', aggfunc=['mean','sum'], fill_value=0)
print("Bölgelere göre ürünlerin toplam satışları (Pivot Tablo, NaN=0):\n")
pivot_satis_toplam

Bölgelere göre ürünlerin toplam satışları (Pivot Tablo, NaN=0):

         mean                                     sum
      Maliyet              Satış              Maliyet          Satış
Ürün        A     B     C      A      B     C       A    B   C     A    B    C
Bölge
Batı     55.0   0.0   0.0  110.0    0.0   0.0      55    0   0   110    0    0
Doğu      0.0   0.0  42.5    0.0    0.0  85.0       0    0  85     0    0  170
Güney     0.0  80.0   0.0    0.0  175.0   0.0       0  160   0     0  350    0
Kuzey    55.0  65.0   0.0  110.0  130.0   0.0     110   65   0   220  130    0